category: network
points:   200
name:     DNS-сервера
author:   nsychev
description: >
    <p>Интернет — изобретение спецслужб Запада. И им мало того, что они собирают все-все
    данные о нас, они ещё и пихают уязвимости в своё ПО!</p>
    <p>Всем должно стать очевидно, что пора делать свои DNS-сервера, правильные и хорошие.</p>
requires: (admin)
flags:
    - "uctf_r341_digg3r_3xp3rt"
hints:
    -
        name:   hint
        points: 50
        text:   Какую информацию можно слить с DNS-сервера и как?
    -
        name:   hint2
        points: 70
        text:   В каких случаях DNS работает по TCP?

