category: misc
points:   10
name:     Welcome aboard
author:   vanyaklimenko
description: >
    <p>«Добро пожаловать в <strong>Банк Банк</strong>! Наш банк предоставляет услуги
    частным лицам с 1337 года. Мы предлагаем полный спектр банковских инструментов, 
    и вы можете быть уверены, что все ваши сбережения в полной безопасности,» — 
    сказал нам пресс-секретарь Банка.</p>
    <p>Однако, уже с первого взгляда видно, что эта история выглядит слишком радужно.</p>
    <p>Ваша миссия на сегодня — узнать всё о банке: как снаружи, так и изнутри.
    Найти все слабые места и пролезть всюду, куда получится.</p>
    <p>Будьте аккуратны и ничего не ломайте, иначе служба безопасности немедленно
    появится на горизонте.</p>
    <p>За всю найденную интересную информацию вы получите заслуженную награду.
    Удачи в раскрытии тайн!</p>
    <p><i>Первый флаг совсем близко...</i></p>
urls:
    - https://bankbank.exposed/
flags:
    - "uctfgoahead"

